wordbook/urls.py
from django.urls import path

from . import views

app_name = "wordbook"

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register, name="register"),
    path("select", views.select, name="select"),
    path("wordlist", views.wordlist, name="wordlist"),
    path("quiz", views.quiz, name="quiz"),
    path("answer", views.answer, name="answer"),
]

wordbook_pj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wordbook.urls")),
]

wordbook/models.py
from django.db import models

# Create your models here.


class Word(models.Model):
    en_word = models.CharField(max_length=50)
    ja_word = models.CharField(max_length=50)
    en_to_ja_correct_count = models.PositiveIntegerField(default=0)
    en_to_ja_incorrect_count = models.PositiveIntegerField(default=0)
    ja_to_en_correct_count = models.PositiveIntegerField(default=0)
    ja_to_en_incorrect_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.en_word

wordbook/views.py
import re
from urllib.parse import urlencode  # 追加

from django.shortcuts import get_object_or_404, redirect, render  # 追加
from django.urls import reverse  # 追加

from .models import Word


def index(request):
    return render(request, "wordbook/index.html")


def register(request):
    def is_english(word):  # 追加
        pattern = re.compile("[a-zA-Z]+")
        result = pattern.fullmatch(word)
        if result:
            return True
        else:
            return False

    def is_japanese(word):  # 追加
        pattern = re.compile("[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]+")
        result = pattern.fullmatch(word)
        if result:
            return True
        else:
            return False

    try:
        context = {
            "message": request.GET["message"],
        }
    except:
        context = {}

    if request.method == "POST":
        en_word = request.POST["en_word"]
        ja_word = request.POST["ja_word"]

        if is_english(en_word) and is_japanese(ja_word):  # 追加
            Word.objects.create(en_word=en_word, ja_word=ja_word)
            message = en_word + "が作成されました。"
        else:
            message = "正しい文字列を入力してください。"

        redirect_url = reverse("wordbook:register")
        params = urlencode(
            {
                "message": message,  # 変更
            }
        )
        url = str(redirect_url) + "?" + str(params)
        return redirect(url)

    return render(request, "wordbook/register.html", context)


def select(request):  # 追加
    if request.method == "POST":
        mode = request.POST["mode"]
        style = request.POST["style"]
        how_many = request.POST["how_many"]

        redirect_url = reverse("wordbook:quiz")
        params = urlencode(
            {
                "mode": mode,
                "style": style,
                "how_many": how_many,
            }
        )
        url = redirect_url + "?" + params
        return redirect(url)

    return render(request, "wordbook/select.html")


def wordlist(request):
    context = {
        "words": Word.objects.all(),
    }
    return render(request, "wordbook/wordlist.html", context)


# 省略


def quiz(request):  # 追加
    mode = request.GET["mode"]
    style = request.GET["style"]

    try:
        how_many = int(request.GET["how_many"])
    except ValueError:
        how_many = 0
        print("ValueError発生")

    all_words = Word.objects.all()

    all_word_counts = all_words.count()
    if how_many > all_word_counts:
        how_many = all_word_counts

    if request.method == "GET":
        if style == "often_wrong":
            if mode == "en_to_ja":
                words = all_words.filter(en_to_ja_correct_count__lt=3).order_by(
                    "-en_to_ja_incorrect_count"
                )[:how_many]
            else:
                words = all_words.filter(ja_to_en_correct_count__lt=3).order_by(
                    "-ja_to_en_incorrect_count"
                )[:how_many]
        else:
            words = all_words.order_by("?")[:how_many]

        context = {
            "mode": mode,
            "style": style,
            "how_many": how_many,
            "words": words,
        }

    elif request.method == "POST":
        info = {
            "mode": mode,
            "style": style,
            "how_many": how_many,
        }

        word_ids = dict()
        answers = dict()
        if mode == "en_to_ja":
            for i in range(1, how_many + 1):
                try:
                    answer = request.POST["question_" + str(i)]
                    answers["answer" + str(i)] = answer
                    word_id = int(request.POST["word_" + str(i)])
                    word_ids["word_id" + str(i)] = word_id
                    word = all_words.get(pk=word_id)
                    if answer == word.ja_word:
                        word.en_to_ja_correct_count += 1
                        word.save()
                    else:
                        word.en_to_ja_incorrect_count += 1
                        word.save()
                except ValueError:
                    print("ValueError発生")
        else:
            for i in range(1, how_many + 1):
                try:
                    answer = request.POST["question_" + str(i)]
                    answers["answer" + str(i)] = answer
                    word_id = int(request.POST["word_" + str(i)])
                    word_ids["word_id" + str(i)] = word_id
                    word = all_words.get(pk=word_id)
                    if answer == word.en_word:
                        word.ja_to_en_correct_count += 1
                        word.save()
                    else:
                        word.ja_to_en_incorrect_count += 1
                        word.save()
                except ValueError:
                    print("ValueError発生")

        redirect_url = reverse("wordbook:answer")
        params = urlencode(dict(info | word_ids | answers))
        url = str(redirect_url) + "?" + str(params)
        return redirect(url)

    return render(request, "wordbook/quiz.html", context)


def answer(request):  # 追加
    try:
        how_many = int(request.GET["how_many"])
    except ValueError:
        how_many = 0
        print("ValueError発生")

    info = list()
    for i in range(1, how_many + 1):
        word_id = request.GET["word_id" + str(i)]
        word = get_object_or_404(Word, pk=word_id)
        answer = request.GET["answer" + str(i)]

        q_and_a = {
            "word": word,
            "answer": answer,
        }

        info.append(q_and_a)

    context = {
        "mode": request.GET["mode"],
        "style": request.GET["style"],
        "how_many": how_many,
        "info": info,
    }

    return render(request, "wordbook/answer.html", context)

wordbook/templates/wordbook/answer.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>英単語暗記アプリ</title>
        <!-- Materialize CSS CDN -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <nav>
                <div class="nav-wrapper">
                    <a href="#" class="brand-logo center">英単語暗記アプリ</a>
                </div>
            </nav>
            <h1 class="center-align">
                全{{ how_many }}問
                {% if mode == "en_to_ja" %}
                英語→日本語
                {% else %}
                日本語→英語
                {% endif %}
                {% if style == "all" %}
                すべての単語
                {% else %}
                よく間違える単語
                {% endif %}
                解答
            </h1>
            <ul class="collection">
                {% if mode == "en_to_ja" %}
                {% for q_and_a in info %}
                <li class="collection-item">
                    <p><strong>{{ q_and_a.word.en_word }}</strong></p>
                    <p>あなたの解答：{{ q_and_a.answer }}</p>
                    <p>
                        {% if q_and_a.answer == q_and_a.word.ja_word %}
                        <span class="green-text">正</span>
                        {% else %}
                        <span class="red-text">誤 正しい答え：{{ q_and_a.word.ja_word }}</span>
                        {% endif %}
                    </p>
                </li>
                {% endfor %}
                {% else %}
                {% for q_and_a in info %}
                <li class="collection-item">
                    <p><strong>{{ q_and_a.word.ja_word }}</strong></p>
                    <p>あなたの解答：{{ q_and_a.answer }}</p>
                    <p>
                        {% if q_and_a.answer == q_and_a.word.en_word %}
                        <span class="green-text">正</span>
                        {% else %}
                        <span class="red-text">誤 正しい答え：{{ q_and_a.word.en_word }}</span>
                        {% endif %}
                    </p>
                </li>
                {% endfor %}
                {% endif %}
            </ul>
            <div class="center-align">
                <a href="{% url 'wordbook:select' %}" class="btn waves-effect waves-light">選択画面に戻る</a>
            </div>
        </div>

        <!-- Materialize JS CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>

</html>

wordbook/templates/wordbook/index.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>英単語暗記アプリ</title>
        <!-- Materialize CSS CDN -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <h2 class="center-align">英単語暗記アプリ</h2>
            <div class="column">
                <div class="col s12 m4">
                    <a href="{% url 'wordbook:select' %}" class="btn waves-effect waves-light full-width">
                        クイズ
                    </a>
                </div>
                <div class="col s12 m4">
                    <a href="{% url 'wordbook:register' %}" class="btn waves-effect waves-light full-width">
                        単語登録
                    </a>
                </div>
                <div class="col s12 m4">
                    <a href="{% url 'wordbook:wordlist' %}" class="btn waves-effect waves-light full-width">
                        単語一覧
                    </a>
                </div>
            </div>
        </div>
        <style>
            .column {
                width: max-content;
                margin: auto;
                margin-bottom: 20px;
            }

            .col {
                margin-top: 30px;
            }

            a {
                width: 200px;
            }

        </style>

        <!-- Materialize JS CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>

</html>

wordbook/templates/wordbook/quiz.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>英単語暗記アプリ</title>
        <!-- Materialize CSS CDN -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <h2 class="center-align">
                全{{ how_many }}問
                {% if mode == "en_to_ja" %}
                英語→日本語
                {% else %}
                日本語→英語
                {% endif %}
                {% if style == "all" %}
                すべての単語
                {% else %}
                よく間違える単語
                {% endif %}
            </h2>
            <form action="" method="POST">
                {% csrf_token %}
                <ol class="collection">
                    {% for word in words %}
                    <li class="collection-item">
                        <div class="input-field">
                            <label for="question_{{ forloop.counter }}">
                                {% if mode == "en_to_ja" %}
                                {{ word.en_word }}
                                {% else %}
                                {{ word.ja_word }}
                                {% endif %}
                            </label>
                            <input type="text" id="question_{{ forloop.counter }}"
                                name="question_{{ forloop.counter }}">
                            <input type="hidden" name="word_{{ forloop.counter }}" value="{{ word.id }}"
                                readonly="readonly">
                        </div>
                    </li>
                    {% endfor %}
                </ol>
                <div class="center-align">
                    <button type="submit" class="btn waves-effect waves-light">
                        解答
                    </button>
                </div>
            </form>
        </div>

        <!-- Materialize JS CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>

</html>

wordbook/templates/wordbook/register.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>英単語暗記アプリ</title>
        <!-- Materialize CSS CDN -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <h2 class="center-align">英単語暗記アプリ</h2>
            <p class="center-align">
                {{ message }}
            </p>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="input-field">
                    <label for="en_word">英語：</label>
                    <input type="text" name="en_word" id="en_word">
                </div>
                <div class="input-field">
                    <label for="ja_word">日本語：</label>
                    <input type="text" name="ja_word" id="ja_word">
                </div>
                <div class="center-align">
                    <button type="submit" class="btn waves-effect waves-light">
                        登録
                    </button>
                </div>
            </form>
            <div class="center-align">
                <a href="{% url 'wordbook:index' %}" class="btn-flat waves-effect">
                    トップに戻る
                </a>
            </div>
        </div>

        <!-- Materialize JS CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>

</html>

wordbook/templates/wordbook/select.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>英単語暗記アプリ</title>
        <!-- Materialize CSS CDN -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <h2 class="center-align">英単語暗記アプリ</h2>
            <form action="" method="POST">
                {% csrf_token %}
                <p>
                    <label>モード：</label>
                    <label>
                        <input type="radio" name="mode" value="en_to_ja">
                        <span>英→日</span>
                    </label>
                    <label>
                        <input type="radio" name="mode" value="ja_to_en">
                        <span>日→英</span>
                    </label>
                </p>
                <p>
                    <label>出題形式：</label>
                    <label>
                        <input type="radio" name="style" value="all">
                        <span>すべての単語</span>
                    </label>
                    <label>
                        <input type="radio" name="style" value="often_wrong">
                        <span>よく間違える単語</span>
                    </label>
                </p>
                <p>
                    <label>問題数：</label>
                    <label>
                        <input type="radio" name="how_many" value="5">
                        <span>5</span>
                    </label>
                    <label>
                        <input type="radio" name="how_many" value="10">
                        <span>10</span>
                    </label>
                    <label>
                        <input type="radio" name="how_many" value="20">
                        <span>20</span>
                    </label>
                </p>
                <div class="center-align">
                    <button type="submit" class="btn waves-effect waves-light">
                        開始
                    </button>
                </div>
            </form>
            <div class="center-align">
                <a href="{% url 'wordbook:index' %}" class="btn-flat waves-effect">
                    トップに戻る
                </a>
            </div>
        </div>
        <style>
            form {
                width: max-content;
                margin: auto;
                margin-bottom: 20px;
            }

        </style>
        <!-- Materialize JS CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>

</html>

wordbook/templates/wordbook/wordlist.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>英単語暗記アプリ</title>
        <!-- Materialize CSS CDN -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            <h2 class="center-align">単語一覧</h2>
            <table class="highlight centered">
                <thead>
                    <tr>
                        <th>英語</th>
                        <th>日本語</th>
                        <th>モード</th>
                        <th>正解数</th>
                        <th>不正解数</th>
                    </tr>
                </thead>
                <tbody>
                    {% for word in words %}
                    <tr>
                        <td rowspan="2">{{ word.en_word }}</td>
                        <td rowspan="2">{{ word.ja_word }}</td>
                        <td>英→日</td>
                        <td>{{ word.en_to_ja_correct_count }}</td>
                        <td>{{ word.en_to_ja_incorrect_count }}</td>
                    </tr>
                    <tr>
                        <td>日→英</td>
                        <td>{{ word.ja_to_en_correct_count }}</td>
                        <td>{{ word.ja_to_en_incorrect_count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="center-align">
                <a href="{% url 'wordbook:index' %}" class="btn-flat waves-effect">
                    トップに戻る
                </a>
            </div>
        </div>

        <!-- Materialize JS CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>

</html>